// Mock Provider for testing - generates simple responses

import { ModelProvider, GenerateOptions } from '../types';

export class MockProvider implements ModelProvider {
  name = 'Mock AI (Testing)';

  async generate(prompt: string, options: GenerateOptions = {}): Promise<string> {
    // Simple mock that echoes back a formatted response
    await new Promise(resolve => setTimeout(resolve, 500)); // Simulate API delay

    return `# Mock AI Response

**Your request**: ${prompt}

## Generated Code:

\`\`\`typescript
/**
 * This is a mock response from the testing provider.
 * In production, this would be actual AI-generated code.
 *
 * Request: ${prompt.slice(0, 50)}${prompt.length > 50 ? '...' : ''}
 */

export function mockFunction() {
  console.log('This is generated by Mock AI');
  // TODO: Replace with actual AI provider (Cheri ML, Gemini, Claude)
  return 'mock-result';
}
\`\`\`

**Note**: This is a mock response. Configure your API keys to use real AI models.
`;
  }
}
